<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            // Waxing Services
            [
                'name' => 'Full Body Scrubbing',
                'description' => 'Complete body exfoliation treatment that removes dead skin cells, leaving your skin smooth, refreshed, and glowing.',
                'category' => 'waxing',
                'duration_minutes' => 90,
                'price_rwf' => 120000,
                'icon' => 'sparkles',
                'sort_order' => 1,
            ],
            [
                'name' => 'Brazilian',
                'description' => 'Professional Brazilian waxing service for complete hair removal with expert care and hygiene.',
                'category' => 'waxing',
                'duration_minutes' => 45,
                'price_rwf' => 25000,
                'icon' => 'star',
                'sort_order' => 2,
            ],
            [
                'name' => 'Bikini Waxing',
                'description' => 'Gentle bikini line waxing for a clean and comfortable result.',
                'category' => 'waxing',
                'duration_minutes' => 30,
                'price_rwf' => 20000,
                'icon' => 'star',
                'sort_order' => 3,
            ],
            [
                'name' => 'Armpits',
                'description' => 'Quick and effective underarm waxing for smooth, hair-free results.',
                'category' => 'waxing',
                'duration_minutes' => 15,
                'price_rwf' => 12000,
                'icon' => 'star',
                'sort_order' => 4,
            ],
            [
                'name' => 'Arms',
                'description' => 'Complete arm waxing service for silky smooth skin from shoulder to wrist.',
                'category' => 'waxing',
                'duration_minutes' => 30,
                'price_rwf' => 20000,
                'icon' => 'star',
                'sort_order' => 5,
            ],
            [
                'name' => 'Upper Leg Waxing',
                'description' => 'Professional upper leg waxing for smooth, hair-free thighs.',
                'category' => 'waxing',
                'duration_minutes' => 35,
                'price_rwf' => 30000,
                'icon' => 'star',
                'sort_order' => 6,
            ],
            [
                'name' => 'Lower Leg Waxing',
                'description' => 'Lower leg waxing from knee to ankle for beautifully smooth legs.',
                'category' => 'waxing',
                'duration_minutes' => 30,
                'price_rwf' => 20000,
                'icon' => 'star',
                'sort_order' => 7,
            ],
            [
                'name' => 'Upper Lip Waxing',
                'description' => 'Precise upper lip waxing for a clean, well-groomed appearance.',
                'category' => 'waxing',
                'duration_minutes' => 10,
                'price_rwf' => 5000,
                'icon' => 'star',
                'sort_order' => 8,
            ],
            [
                'name' => 'Chin',
                'description' => 'Quick and effective chin waxing for smooth facial skin.',
                'category' => 'waxing',
                'duration_minutes' => 10,
                'price_rwf' => 5000,
                'icon' => 'star',
                'sort_order' => 9,
            ],
            [
                'name' => 'Full Face',
                'description' => 'Complete facial waxing service including upper lip, chin, cheeks, and forehead.',
                'category' => 'waxing',
                'duration_minutes' => 25,
                'price_rwf' => 10000,
                'icon' => 'star',
                'sort_order' => 10,
            ],
            [
                'name' => 'Full Vajacial',
                'description' => 'Complete intimate area facial treatment designed to cleanse, exfoliate, and rejuvenate.',
                'category' => 'waxing',
                'duration_minutes' => 60,
                'price_rwf' => 20000,
                'icon' => 'heart',
                'sort_order' => 11,
            ],
            [
                'name' => 'Mini Vajacial',
                'description' => 'Express intimate area facial treatment for quick cleansing and care.',
                'category' => 'waxing',
                'duration_minutes' => 40,
                'price_rwf' => 15000,
                'icon' => 'heart',
                'sort_order' => 12,
            ],
            [
                'name' => 'Full Body Waxing',
                'description' => 'Complete head-to-toe waxing service for all-over smoothness and confidence.',
                'category' => 'waxing',
                'duration_minutes' => 120,
                'price_rwf' => 100000,
                'icon' => 'sparkles',
                'sort_order' => 13,
            ],
            [
                'name' => 'Numbing Spray',
                'description' => 'Topical numbing spray to reduce discomfort during waxing procedures.',
                'category' => 'waxing',
                'duration_minutes' => 5,
                'price_rwf' => 15000,
                'icon' => 'plus',
                'sort_order' => 14,
            ],

            // Makeup Services
            [
                'name' => 'Facial',
                'description' => 'Professional facial treatment to cleanse, exfoliate, and nourish your skin for a healthy, glowing complexion.',
                'category' => 'makeup',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'sparkles',
                'sort_order' => 15,
            ],
            [
                'name' => 'Makeup',
                'description' => 'Expert makeup application for any occasion, from natural everyday looks to glamorous evening styles.',
                'category' => 'makeup',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'heart',
                'sort_order' => 16,
            ],
            [
                'name' => 'Strip Lashes',
                'description' => 'Temporary strip lash application for instant glamour and enhanced eye definition.',
                'category' => 'makeup',
                'duration_minutes' => 20,
                'price_rwf' => 15000,
                'icon' => 'eye',
                'sort_order' => 17,
            ],
            [
                'name' => 'Single Lashes',
                'description' => 'Individual lash extension application for a natural, customized look with long-lasting results.',
                'category' => 'makeup',
                'duration_minutes' => 45,
                'price_rwf' => 25000,
                'icon' => 'eye',
                'sort_order' => 18,
            ],
            [
                'name' => 'Eyebrow Trimming',
                'description' => 'Precise eyebrow shaping and trimming to frame your face perfectly.',
                'category' => 'makeup',
                'duration_minutes' => 15,
                'price_rwf' => 5000,
                'icon' => 'pencil',
                'sort_order' => 19,
            ],
            [
                'name' => 'Henna',
                'description' => 'Natural henna application for eyebrows or hair, providing rich color and conditioning benefits.',
                'category' => 'makeup',
                'duration_minutes' => 30,
                'price_rwf' => 10000,
                'icon' => 'leaf',
                'sort_order' => 20,
            ],

            // Lashes Services
            [
                'name' => 'Classic',
                'description' => 'Classic lash extensions for a natural, enhanced look with one extension per natural lash.',
                'category' => 'lashes',
                'duration_minutes' => 90,
                'price_rwf' => 35000,
                'icon' => 'eye',
                'sort_order' => 21,
            ],
            [
                'name' => 'Classic Full Volume',
                'description' => 'Classic full volume lash extensions for maximum density and dramatic natural-looking lashes.',
                'category' => 'lashes',
                'duration_minutes' => 105,
                'price_rwf' => 35000,
                'icon' => 'eye',
                'sort_order' => 22,
            ],
            [
                'name' => 'Classic Cat Eyes',
                'description' => 'Classic cat eye lash extensions with elongated outer corners for a sultry, lifted appearance.',
                'category' => 'lashes',
                'duration_minutes' => 100,
                'price_rwf' => 35000,
                'icon' => 'eye',
                'sort_order' => 23,
            ],
            [
                'name' => 'Hybrid',
                'description' => 'Hybrid lash extensions combining classic and volume techniques for textured, wispy lashes.',
                'category' => 'lashes',
                'duration_minutes' => 105,
                'price_rwf' => 40000,
                'icon' => 'eye',
                'sort_order' => 24,
            ],
            [
                'name' => 'Hybrid Full Volume',
                'description' => 'Hybrid full volume lash extensions for maximum fullness with a textured, dimensional effect.',
                'category' => 'lashes',
                'duration_minutes' => 120,
                'price_rwf' => 40000,
                'icon' => 'eye',
                'sort_order' => 25,
            ],
            [
                'name' => 'Hybrid Cat Eyes',
                'description' => 'Hybrid cat eye lash extensions with a dramatic winged effect and textured volume.',
                'category' => 'lashes',
                'duration_minutes' => 115,
                'price_rwf' => 40000,
                'icon' => 'eye',
                'sort_order' => 26,
            ],
            [
                'name' => 'Volume',
                'description' => 'Volume lash extensions using multiple lightweight fans for fluffy, dramatic lashes.',
                'category' => 'lashes',
                'duration_minutes' => 120,
                'price_rwf' => 50000,
                'icon' => 'eye',
                'sort_order' => 27,
            ],
            [
                'name' => 'Full Volume',
                'description' => 'Full volume lash extensions with maximum density for the most dramatic, glamorous look.',
                'category' => 'lashes',
                'duration_minutes' => 135,
                'price_rwf' => 50000,
                'icon' => 'eye',
                'sort_order' => 28,
            ],
            [
                'name' => 'Mega Volume',
                'description' => 'Mega volume lash extensions with ultra-fine fans for the fullest, fluffiest possible lashes.',
                'category' => 'lashes',
                'duration_minutes' => 150,
                'price_rwf' => 50000,
                'icon' => 'eye',
                'sort_order' => 29,
            ],
            [
                'name' => 'Mega Volume Cat Eyes',
                'description' => 'Mega volume cat eye lash extensions combining maximum fullness with a winged, lifted effect.',
                'category' => 'lashes',
                'duration_minutes' => 160,
                'price_rwf' => 50000,
                'icon' => 'eye',
                'sort_order' => 30,
            ],
            [
                'name' => 'Refill',
                'description' => 'Lash extension refill service to maintain your existing lash set and fill in any gaps.',
                'category' => 'lashes',
                'duration_minutes' => 60,
                'price_rwf' => 20000,
                'icon' => 'eye',
                'sort_order' => 31,
            ],
            [
                'name' => 'Remove',
                'description' => 'Professional lash extension removal service to safely and gently remove your extensions.',
                'category' => 'lashes',
                'duration_minutes' => 30,
                'price_rwf' => 15000,
                'icon' => 'eye',
                'sort_order' => 32,
            ],

            // Nails Services
            [
                'name' => 'Acrylic & French Gel',
                'description' => 'Acrylic nails with classic French gel tips for an elegant, timeless look.',
                'category' => 'nails',
                'duration_minutes' => 90,
                'price_rwf' => 45000,
                'icon' => 'hand',
                'sort_order' => 33,
            ],
            [
                'name' => 'Acrylic Gel',
                'description' => 'Durable acrylic gel nail application for long-lasting, beautiful nails.',
                'category' => 'nails',
                'duration_minutes' => 75,
                'price_rwf' => 45000,
                'icon' => 'hand',
                'sort_order' => 34,
            ],
            [
                'name' => 'Acrylic Gel Refill',
                'description' => 'Maintenance refill for your existing acrylic gel nails to keep them looking fresh.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 35,
            ],
            [
                'name' => 'Acrylic Colored',
                'description' => 'Vibrant colored acrylic nails in your choice of shades for a bold statement.',
                'category' => 'nails',
                'duration_minutes' => 90,
                'price_rwf' => 60000,
                'icon' => 'hand',
                'sort_order' => 36,
            ],
            [
                'name' => 'Acrylic Colored Powder Refill',
                'description' => 'Refill service for your colored acrylic powder nails to maintain vibrant color.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 37,
            ],
            [
                'name' => 'Acrylic Ombre',
                'description' => 'Stunning ombre gradient effect on acrylic nails for a modern, sophisticated look.',
                'category' => 'nails',
                'duration_minutes' => 105,
                'price_rwf' => 60000,
                'icon' => 'hand',
                'sort_order' => 38,
            ],
            [
                'name' => 'French Gel Nature',
                'description' => 'Natural French gel manicure with subtle, elegant tips for a polished appearance.',
                'category' => 'nails',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'hand',
                'sort_order' => 39,
            ],
            [
                'name' => 'French Tips',
                'description' => 'Classic French tip manicure with white tips and natural pink base.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 40,
            ],
            [
                'name' => 'Gel Application',
                'description' => 'Professional gel polish application for glossy, chip-resistant nails.',
                'category' => 'nails',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'hand',
                'sort_order' => 41,
            ],
            [
                'name' => 'Gum Gel',
                'description' => 'Flexible gum gel nails that provide strength and durability with natural movement.',
                'category' => 'nails',
                'duration_minutes' => 75,
                'price_rwf' => 40000,
                'icon' => 'hand',
                'sort_order' => 42,
            ],
            [
                'name' => 'Manicure + Massaging',
                'description' => 'Complete manicure service with hand massage, nail shaping, cuticle care, and polish.',
                'category' => 'nails',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'hand',
                'sort_order' => 43,
            ],
            [
                'name' => 'Pedicure',
                'description' => 'Relaxing pedicure with foot soak, nail care, exfoliation, and polish application.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 25000,
                'icon' => 'hand',
                'sort_order' => 44,
            ],
            [
                'name' => 'Matte Gel',
                'description' => 'Trendy matte finish gel nails for a modern, non-glossy sophisticated look.',
                'category' => 'nails',
                'duration_minutes' => 50,
                'price_rwf' => 20000,
                'icon' => 'hand',
                'sort_order' => 45,
            ],
            [
                'name' => 'Overlays & Gel',
                'description' => 'Protective gel overlay to strengthen natural nails while maintaining their length.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'hand',
                'sort_order' => 46,
            ],
            [
                'name' => 'Sculpted Acrylic French (Full Set)',
                'description' => 'Hand-sculpted acrylic nails with French tips for a customized, perfect fit.',
                'category' => 'nails',
                'duration_minutes' => 120,
                'price_rwf' => 65000,
                'icon' => 'hand',
                'sort_order' => 47,
            ],
            [
                'name' => 'Sculpted & Gel',
                'description' => 'Sculpted gel nail extensions for natural-looking length and strength.',
                'category' => 'nails',
                'duration_minutes' => 90,
                'price_rwf' => 50000,
                'icon' => 'hand',
                'sort_order' => 48,
            ],
            [
                'name' => 'Sculpted Acrylic Ombre',
                'description' => 'Hand-sculpted acrylic nails with beautiful ombre gradient coloring.',
                'category' => 'nails',
                'duration_minutes' => 120,
                'price_rwf' => 65000,
                'icon' => 'hand',
                'sort_order' => 49,
            ],
            [
                'name' => 'Sticks & Gel',
                'description' => 'Gel application with stick-on nail enhancements for quick, beautiful results.',
                'category' => 'nails',
                'duration_minutes' => 45,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 50,
            ],
            [
                'name' => 'Tips & Gel',
                'description' => 'Nail tips with gel overlay for added length and durability.',
                'category' => 'nails',
                'duration_minutes' => 75,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 51,
            ],
            [
                'name' => 'Tips Refill',
                'description' => 'Refill service for existing nail tips to maintain length and appearance.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'hand',
                'sort_order' => 52,
            ],
            [
                'name' => 'Tips & Overlays',
                'description' => 'Nail tips with protective overlay for enhanced strength and longevity.',
                'category' => 'nails',
                'duration_minutes' => 75,
                'price_rwf' => 35000,
                'icon' => 'hand',
                'sort_order' => 53,
            ],
            [
                'name' => 'Gel Remove',
                'description' => 'Safe and gentle removal of gel polish without damaging natural nails.',
                'category' => 'nails',
                'duration_minutes' => 20,
                'price_rwf' => 10000,
                'icon' => 'hand',
                'sort_order' => 54,
            ],
            [
                'name' => 'Chrome',
                'description' => 'Metallic chrome powder finish for dazzling, mirror-like nails.',
                'category' => 'nails',
                'duration_minutes' => 60,
                'price_rwf' => 30000,
                'icon' => 'hand',
                'sort_order' => 55,
            ],
            [
                'name' => 'Nail Decoration',
                'description' => 'Custom nail art and decorative embellishments to personalize your manicure.',
                'category' => 'nails',
                'duration_minutes' => 30,
                'price_rwf' => 10000,
                'icon' => 'sparkles',
                'sort_order' => 56,
            ],
            [
                'name' => 'Gel Cream Application',
                'description' => 'Nourishing gel cream treatment to hydrate and strengthen nails.',
                'category' => 'nails',
                'duration_minutes' => 30,
                'price_rwf' => 15000,
                'icon' => 'hand',
                'sort_order' => 57,
            ],
            [
                'name' => 'Acry Gel',
                'description' => 'Hybrid acrylic-gel system combining the best of both for durable, flexible nails.',
                'category' => 'nails',
                'duration_minutes' => 75,
                'price_rwf' => 40000,
                'icon' => 'hand',
                'sort_order' => 58,
            ],
            [
                'name' => 'Curly Cut Full',
                'description' => 'Specialized full nail service with unique curly cut design and shaping.',
                'category' => 'nails',
                'duration_minutes' => 120,
                'price_rwf' => 70000,
                'icon' => 'sparkles',
                'sort_order' => 59,
            ],
            [
                'name' => 'Soak Off',
                'description' => 'Gentle soak-off removal process for acrylic or gel nails.',
                'category' => 'nails',
                'duration_minutes' => 30,
                'price_rwf' => 10000,
                'icon' => 'hand',
                'sort_order' => 60,
            ],

            // Hair Services
            [
                'name' => 'Finger Waves',
                'description' => 'Classic finger wave hairstyle creating elegant S-shaped waves for a vintage, sophisticated look.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 65000,
                'icon' => 'scissors',
                'sort_order' => 61,
            ],
            [
                'name' => 'Flat Ironing and Trimming',
                'description' => 'Professional flat iron styling with precision trimming for smooth, sleek, healthy hair.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 50000,
                'icon' => 'scissors',
                'sort_order' => 62,
            ],
            [
                'name' => 'Bantu Knots',
                'description' => 'Traditional Bantu knot styling creating beautiful spiral curls when unraveled.',
                'category' => 'hair',
                'duration_minutes' => 75,
                'price_rwf' => 35000,
                'icon' => 'sparkles',
                'sort_order' => 63,
            ],
            [
                'name' => 'Black Color',
                'description' => 'Deep black hair coloring for rich, glossy color and full coverage.',
                'category' => 'hair',
                'duration_minutes' => 75,
                'price_rwf' => 20000,
                'icon' => 'pencil',
                'sort_order' => 64,
            ],
            [
                'name' => 'Boy Hair Cut',
                'description' => 'Classic boys haircut with clean lines and age-appropriate styling.',
                'category' => 'hair',
                'duration_minutes' => 30,
                'price_rwf' => 20000,
                'icon' => 'scissors',
                'sort_order' => 65,
            ],
            [
                'name' => 'Coloring Dreadlocs Full',
                'description' => 'Complete dreadloc coloring service for vibrant, full-coverage color throughout.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 25000,
                'icon' => 'pencil',
                'sort_order' => 66,
            ],
            [
                'name' => 'Coloring Dreadlocs Half',
                'description' => 'Partial dreadloc coloring for subtle highlights or ombre effects.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 20000,
                'icon' => 'pencil',
                'sort_order' => 67,
            ],
            [
                'name' => 'Consultation',
                'description' => 'Professional hair consultation to discuss styles, treatments, and personalized recommendations.',
                'category' => 'hair',
                'duration_minutes' => 20,
                'price_rwf' => 10000,
                'icon' => 'heart',
                'sort_order' => 68,
            ],
            [
                'name' => 'Dreadlocs Retouch',
                'description' => 'Maintenance retouch for existing dreadlocs to keep them neat and well-formed.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 35000,
                'icon' => 'scissors',
                'sort_order' => 69,
            ],
            [
                'name' => 'Fresh Dreadlocs',
                'description' => 'Complete new dreadloc installation from start to finish for a fresh protective style.',
                'category' => 'hair',
                'duration_minutes' => 240,
                'price_rwf' => 150000,
                'icon' => 'sparkles',
                'sort_order' => 70,
            ],
            [
                'name' => 'Fresh Relaxing Inclusive of Treatment and Trim',
                'description' => 'Complete relaxer service including deep conditioning treatment and precision trim.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 50000,
                'icon' => 'scissors',
                'sort_order' => 71,
            ],
            [
                'name' => 'Full Color',
                'description' => 'Complete all-over hair coloring for dramatic transformation and full coverage.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 70000,
                'icon' => 'pencil',
                'sort_order' => 72,
            ],
            [
                'name' => 'Gentleman\'s Cut',
                'description' => 'Classic gentleman\'s haircut with refined styling and attention to detail.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 25000,
                'icon' => 'scissors',
                'sort_order' => 73,
            ],
            [
                'name' => 'Hair Color Full Head Long Hair',
                'description' => 'Complete color service for long hair requiring extra product and time.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 150000,
                'icon' => 'pencil',
                'sort_order' => 74,
            ],
            [
                'name' => 'Haircut',
                'description' => 'Standard haircut service tailored to your desired style and length.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'scissors',
                'sort_order' => 75,
            ],
            [
                'name' => 'Half Color',
                'description' => 'Partial hair coloring for highlights, lowlights, or ombre effects.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 50000,
                'icon' => 'pencil',
                'sort_order' => 76,
            ],
            [
                'name' => 'Highlight Color Big Chop 1/2 Step Process',
                'description' => 'Highlight coloring with big chop and multi-step processing for dramatic results.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 70000,
                'icon' => 'pencil',
                'sort_order' => 77,
            ],
            [
                'name' => 'Ladies Premier Cut/Sponge Curls',
                'description' => 'Premium ladies haircut with sponge curl styling for bouncy, defined curls.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'scissors',
                'sort_order' => 78,
            ],
            [
                'name' => 'Line Up',
                'description' => 'Precision edge line-up for clean, sharp hairline definition.',
                'category' => 'hair',
                'duration_minutes' => 20,
                'price_rwf' => 10000,
                'icon' => 'scissors',
                'sort_order' => 79,
            ],
            [
                'name' => 'Own Color and Relaxer',
                'description' => 'Bring your own color and relaxer products for professional application.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 50000,
                'icon' => 'pencil',
                'sort_order' => 80,
            ],
            [
                'name' => 'Platinum and Grey Color',
                'description' => 'Ultra-light platinum or trendy grey color requiring advanced bleaching and toning.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 100000,
                'icon' => 'pencil',
                'sort_order' => 81,
            ],
            [
                'name' => 'Platinum/Pastel Color + Big Chop',
                'description' => 'Platinum or pastel color combined with big chop for a bold, fresh transformation.',
                'category' => 'hair',
                'duration_minutes' => 150,
                'price_rwf' => 80000,
                'icon' => 'pencil',
                'sort_order' => 82,
            ],
            [
                'name' => 'Relaxing or Retouching Chemical',
                'description' => 'Chemical relaxer or retouch service to straighten and smooth textured hair.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 35000,
                'icon' => 'scissors',
                'sort_order' => 83,
            ],
            [
                'name' => 'Straw Set Half',
                'description' => 'Partial straw set styling for defined curls and vintage-inspired volume.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 35000,
                'icon' => 'sparkles',
                'sort_order' => 84,
            ],
            [
                'name' => 'Straw Set/Perm Rod Set Curls Natural Hair',
                'description' => 'Full straw or perm rod set on natural hair for bouncy, lasting curls.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 50000,
                'icon' => 'sparkles',
                'sort_order' => 85,
            ],
            [
                'name' => 'Texturizing',
                'description' => 'Hair texturizing treatment to add body, movement, and definition to your style.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 20000,
                'icon' => 'scissors',
                'sort_order' => 86,
            ],
            [
                'name' => 'Treatment',
                'description' => 'Deep conditioning hair treatment to restore moisture, strength, and shine.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 40000,
                'icon' => 'heart',
                'sort_order' => 87,
            ],
            [
                'name' => 'Under Cut',
                'description' => 'Trendy undercut styling with shaved sides or back for an edgy look.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'scissors',
                'sort_order' => 88,
            ],
            [
                'name' => 'Wash and Set Short Hair Natural',
                'description' => 'Wash and set service for short natural hair with styling and finishing.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 15000,
                'icon' => 'scissors',
                'sort_order' => 89,
            ],
            [
                'name' => 'You Got Me Twisted',
                'description' => 'Creative twist-out styling for defined, textured curls and natural movement.',
                'category' => 'hair',
                'duration_minutes' => 75,
                'price_rwf' => 50000,
                'icon' => 'sparkles',
                'sort_order' => 90,
            ],
            [
                'name' => 'Pixie Cut',
                'description' => 'Chic pixie cut with precise layering and personalized shape for a modern, low-maintenance style.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 75000,
                'icon' => 'scissors',
                'sort_order' => 91,
            ],
            [
                'name' => 'Pixie Cut Highlight (Tips, Tricks)',
                'description' => 'Pixie cut with highlight coloring including advanced techniques and styling tips.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 100000,
                'icon' => 'pencil',
                'sort_order' => 92,
            ],
            [
                'name' => 'Bob Cut',
                'description' => 'Classic bob haircut with clean lines and versatile styling options.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 75000,
                'icon' => 'scissors',
                'sort_order' => 93,
            ],
            [
                'name' => 'Undo Hair',
                'description' => 'Reversal or removal service for previous hair treatments or styles.',
                'category' => 'hair',
                'duration_minutes' => 30,
                'price_rwf' => 10000,
                'icon' => 'scissors',
                'sort_order' => 94,
            ],
            [
                'name' => 'Undo Dreadlocks',
                'description' => 'Professional dreadlock removal and detangling service to restore loose hair.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 65000,
                'icon' => 'scissors',
                'sort_order' => 95,
            ],
            [
                'name' => 'Styling',
                'description' => 'Professional hair styling service for any desired look or occasion.',
                'category' => 'hair',
                'duration_minutes' => 30,
                'price_rwf' => 15000,
                'icon' => 'sparkles',
                'sort_order' => 96,
            ],
            [
                'name' => 'Styling Wig',
                'description' => 'Custom wig styling, cutting, and customization for a natural, personalized fit.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 20000,
                'icon' => 'sparkles',
                'sort_order' => 97,
            ],
            [
                'name' => 'Sisterlocks',
                'description' => 'Complete sisterlock installation creating tiny, uniform locs for a refined protective style.',
                'category' => 'hair',
                'duration_minutes' => 480,
                'price_rwf' => 350000,
                'icon' => 'sparkles',
                'sort_order' => 98,
            ],
            [
                'name' => 'Sisterlocks Retouch',
                'description' => 'Maintenance retouch for existing sisterlocks to keep them tight and neat.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 75000,
                'icon' => 'scissors',
                'sort_order' => 99,
            ],
            [
                'name' => 'Wash and Set',
                'description' => 'Complete wash and set service with styling for polished, salon-fresh hair.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 25000,
                'icon' => 'scissors',
                'sort_order' => 100,
            ],
            [
                'name' => 'Beard',
                'description' => 'Professional beard trimming, shaping, and grooming for a well-maintained look.',
                'category' => 'hair',
                'duration_minutes' => 20,
                'price_rwf' => 10000,
                'icon' => 'scissors',
                'sort_order' => 101,
            ],
            [
                'name' => 'Weave Pixie Cut',
                'description' => 'Pixie cut styled with weave installation for added volume and versatility.',
                'category' => 'hair',
                'duration_minutes' => 150,
                'price_rwf' => 120000,
                'icon' => 'sparkles',
                'sort_order' => 102,
            ],
            [
                'name' => 'Amber Rose Low Cut',
                'description' => 'Ultra-short buzz cut inspired by Amber Rose\'s signature bold style.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 75000,
                'icon' => 'scissors',
                'sort_order' => 103,
            ],
            [
                'name' => 'Silk Press',
                'description' => 'Smooth silk press treatment for sleek, straight hair with heat styling and shine.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 75000,
                'icon' => 'scissors',
                'sort_order' => 104,
            ],
            [
                'name' => 'Finger Coils/Finger Waves',
                'description' => 'Finger coil or finger wave styling for defined, elegant wave patterns.',
                'category' => 'hair',
                'duration_minutes' => 90,
                'price_rwf' => 50000,
                'icon' => 'sparkles',
                'sort_order' => 105,
            ],
            [
                'name' => 'Weaving',
                'description' => 'Professional weave installation for length, volume, and protective styling.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 100000,
                'icon' => 'sparkles',
                'sort_order' => 106,
            ],
            [
                'name' => 'Braids',
                'description' => 'Protective braiding service in various styles including box braids, cornrows, and more.',
                'category' => 'hair',
                'duration_minutes' => 180,
                'price_rwf' => 45000,
                'icon' => 'sparkles',
                'sort_order' => 107,
            ],
            [
                'name' => 'Rod Sets',
                'description' => 'Full rod set styling creating uniform, bouncy curls with lasting definition.',
                'category' => 'hair',
                'duration_minutes' => 120,
                'price_rwf' => 80000,
                'icon' => 'sparkles',
                'sort_order' => 108,
            ],
            [
                'name' => 'Pixie Cut Styling Only',
                'description' => 'Styling service for existing pixie cut without cutting.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 50000,
                'icon' => 'sparkles',
                'sort_order' => 109,
            ],
            [
                'name' => 'Retouch Color',
                'description' => 'Root retouch color service to maintain consistent color from roots to ends.',
                'category' => 'hair',
                'duration_minutes' => 75,
                'price_rwf' => 50000,
                'icon' => 'pencil',
                'sort_order' => 110,
            ],
            [
                'name' => 'Curly Cut Half',
                'description' => 'Specialized curly haircut technique focusing on curl pattern and natural shape.',
                'category' => 'hair',
                'duration_minutes' => 60,
                'price_rwf' => 50000,
                'icon' => 'scissors',
                'sort_order' => 111,
            ],
            [
                'name' => 'Kids Hair Cut',
                'description' => 'Gentle, child-friendly haircut service for kids of all ages.',
                'category' => 'hair',
                'duration_minutes' => 30,
                'price_rwf' => 15000,
                'icon' => 'scissors',
                'sort_order' => 112,
            ],
            [
                'name' => 'Wash and Dry',
                'description' => 'Simple wash and blow-dry service for clean, styled hair.',
                'category' => 'hair',
                'duration_minutes' => 45,
                'price_rwf' => 25000,
                'icon' => 'scissors',
                'sort_order' => 113,
            ],

            // Tattoo and Piercing Services
            [
                'name' => 'Custom Tattoo',
                'description' => 'Custom tattoo design tailored to your vision. Pricing negotiable based on size, complexity, and placement. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 120,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 114,
            ],
            [
                'name' => 'Small Tattoo',
                'description' => 'Small-sized tattoo design. Final price depends on design complexity and detail. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 60,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 115,
            ],
            [
                'name' => 'Medium Tattoo',
                'description' => 'Medium-sized tattoo design. Pricing varies based on design intricacy and time required. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 120,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 116,
            ],
            [
                'name' => 'Large Tattoo',
                'description' => 'Large-sized tattoo design or sleeve work. Price negotiable based on design scope and sessions needed. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 180,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 117,
            ],
            [
                'name' => 'Tattoo Cover-Up',
                'description' => 'Cover-up tattoo service to transform or conceal existing tattoos. Pricing based on size and complexity. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 150,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 118,
            ],
            [
                'name' => 'Tattoo Touch-Up',
                'description' => 'Touch-up service for existing tattoos to refresh colors and lines. Contact for pricing.',
                'category' => 'tattoo',
                'duration_minutes' => 60,
                'price_rwf' => 0,
                'icon' => 'pencil',
                'sort_order' => 119,
            ],
            [
                'name' => 'Tattoo Consultation',
                'description' => 'Professional consultation to discuss design ideas, placement, and pricing. Contact to schedule.',
                'category' => 'tattoo',
                'duration_minutes' => 30,
                'price_rwf' => 0,
                'icon' => 'heart',
                'sort_order' => 120,
            ],
            [
                'name' => 'Cheek Piercing',
                'description' => 'Professional cheek piercing service with quality jewelry. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 30,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 121,
            ],
            [
                'name' => 'Conch Piercing',
                'description' => 'Inner or outer conch ear piercing with expert technique. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 122,
            ],
            [
                'name' => 'Daith Piercing',
                'description' => 'Daith ear piercing with professional care and sterilization. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 123,
            ],
            [
                'name' => 'Ear Piercing',
                'description' => 'Standard ear lobe or cartilage piercing service. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 15,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 124,
            ],
            [
                'name' => 'Eyebrow Piercing',
                'description' => 'Eyebrow piercing with precision placement and quality jewelry. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 125,
            ],
            [
                'name' => 'Helix Piercing',
                'description' => 'Helix ear piercing on the upper cartilage rim. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 126,
            ],
            [
                'name' => 'Industrial Piercing',
                'description' => 'Industrial bar piercing through two points of ear cartilage. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 30,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 127,
            ],
            [
                'name' => 'Lip Piercing',
                'description' => 'Lip piercing service including labret, snake bites, or other lip placements. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 128,
            ],
            [
                'name' => 'Monroe Piercing',
                'description' => 'Monroe piercing above the upper lip for a classic beauty mark look. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 129,
            ],
            [
                'name' => 'Navel Piercing',
                'description' => 'Professional belly button piercing with aftercare instructions. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 25,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 130,
            ],
            [
                'name' => 'Nose Piercing',
                'description' => 'Nostril or septum nose piercing with quality jewelry options. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 131,
            ],
            [
                'name' => 'Tongue Piercing',
                'description' => 'Tongue piercing with professional technique and sterilization. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 25,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 132,
            ],
            [
                'name' => 'Tragus Piercing',
                'description' => 'Tragus ear piercing on the small cartilage flap. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 20,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 133,
            ],
            [
                'name' => 'Jewelry Change',
                'description' => 'Professional jewelry change service for existing piercings. Contact for pricing.',
                'category' => 'piercing',
                'duration_minutes' => 10,
                'price_rwf' => 0,
                'icon' => 'star',
                'sort_order' => 134,
            ],
        ];

        foreach ($services as $service) {
            Service::create([
                ...$service,
                'slug' => Str::slug($service['name']),
                'is_active' => true,
            ]);
        }
    }
}
